### ISSUE TITLE
syntastic: error: checker python/python returned abnormal status 1

### ISSUE THREAD

**Issue by danalsan** [vim-syntastic/syntastic#1937]
Same symptoms as https://github.com/vim-syntastic/syntastic/issues/1131 but apparently different root cause

:SyntasticInfo output

```
Syntastic version: 3.8.0-10 (Vim 800, Linux)
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
syntastic: 4.324299: system: command run in 0.230407s
syntastic: 4.331391: system: command run in 0.006002s
Available checkers: flake8 pep8 pycodestyle pyflakes pylint python
Currently enabled checkers: python flake8 pylint
syntastic: 4.332797: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &she
llxescape = ''
```

When saving a py file with syntactic errors:

```
Flake8 found issues
syntastic: 61.174707: g:syntastic_version = '3.8.0-10 (Vim 800, Linux)'
syntastic: 61.174808: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &sh
ellxescape = ''
syntastic: 61.175078: UpdateErrors (auto): default checkers
syntastic: 61.175305: CacheErrors: default checkers
syntastic: 61.175740: g:syntastic_aggregate_errors = 0
syntastic: 61.175876: getcwd() = '/home/dani/personal/botijo'
syntastic: 61.176323: CacheErrors: Invoking checker: python/python
syntastic: 61.176823: SyntasticMake: called with options: {'errorformat': '%E%f:%l:%c: %m', 'makeprg': 'python /home/dani/.vim/bundle/syntastic/syntax_checkers/python/compile.py ''''', 'env'
: {'TERM': 'dumb'}, 'returns': [0]}
syntastic: 61.195610: system: command run in 0.018481s
syntastic: 61.195761: checker output: ['Traceback (most recent call last):', '  File "/home/dani/.vim/bundle/syntastic/syntax_checkers/python/compile.py", line 11, in <module>', '    compile
(open(argv[1]).read(), argv[1], ''exec'', 0, 1)', 'IOError: [Errno 2] No such file or directory: ''''', '']
syntastic: error: checker python/python returned abnormal status 1
syntastic: 61.196182: python/python raw: []
syntastic: 61.196321: quiet_messages filter: {}
syntastic: 61.196417: getLocList: checker python/python run in 0.020011s
syntastic: 61.196663: CacheErrors: Invoking checker: python/flake8
syntastic: 61.197173: SyntasticMake: called with options: {'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#', 'makeprg': 'flake8 ''''', 'env': {
'TERM': 'dumb'}}
syntastic: 61.519042: system: command run in 0.321586s
syntastic: 61.519183: checker output: ['Traceback (most recent call last):', '  File "/usr/bin/flake8", line 9, in <module>', '    load_entry_point(''flake8==2.5.5'', ''console_scripts'', ''
flake8'')()', '  File "/usr/lib/python2.7/site-packages/flake8/main.py", line 36, in main', '    report = flake8_style.check_files()', '  File "/usr/lib/python2.7/site-packages/flake8/engine
.py", line 181, in check_files', '    return self._retry_serial(self._styleguide.check_files, paths=paths)', '  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_
serial', '    return func(*args, **kwargs)', '  File "/usr/lib/python2.7/site-packages/pep8.py", line 1832, in check_files', '    runner(path)', '  File "/usr/lib/python2.7/site-packages/fla
ke8/engine.py", line 126, in input_file', '    return fchecker.check_all(expected=expected, line_offset=line_offset)', '  File "/usr/lib/python2.7/site-packages/pep8.py", line 1564, in check
_all', '    self.check_ast()', '  File "/usr/lib/python2.7/site-packages/pep8.py", line 1510, in check_ast', '    checker = cls(tree, self.filename)', '  File "/usr/lib/python2.7/site-packag
es/flake8/_pyflakes.py", line 45, in __init__', '    filename = pep8.normalize_paths(filename)[0]', 'IndexError: list index out of range', '']
```
Although the main error looks related to the python checker, flake8 returns also "IndexError: list index out of range" which I don't know if that's a bug or not. Running flake8 on my file just returns this message:
```
syntest.py:34:1: F821 undefined name 'a'
```
Also, I have tried :SyntasticReset and have no variables defined in my .vimrc apart from the debug level.
Thanks!
Daniel

**Comment by danalsan** [comment]
Looking back into issue https://github.com/vim-syntastic/syntastic/issues/1924, I found that this failure is also related to Plugin nvie/vim-flake8 enabled.
After disabling this plugin, syntastic works as expected again. Not sure if this is a bug or completely unrelated but maybe worth to mention. Since syntastic already have a flake8 checker there's no point to have it enabled but it shouldn't conflict I guess.
Thanks!
Daniel

**Comment by lcd047** [comment]
> Not sure if this is a bug or completely unrelated but maybe worth to mention.

Yes.  Presumably that's why it was mentioned in #1924. :smile:

> Since syntastic already have a flake8 checker there's no point to have it enabled but it shouldn't conflict I guess.

Out of curiosity, why do you expect it to bne fixed in syntastic that has to deal with >200 checkers, rather than in `nvie/vim-flake8` that deals with a single one?
