### ISSUE TITLE
flake8 checker doesn't work, but pep8 checker does

### ISSUE THREAD

**Issue by r631269** [vim-syntastic/syntastic#2107]
Syntastic checking works great in almost all situations, but not flake8 in gui macvim 8. The pep8 works fine, and both pep8 and flake8 work from terminal macvim.

When I set `let g:syntastic_python_checkers=['flake8']` I get the following
```
syntastic: 273300.366379: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shell
xquote = '', &shellxescape = ''
syntastic: 273300.366743: UpdateErrors: default checkers
syntastic: 273300.367244: CacheErrors: default checkers
syntastic: 273300.368872: g:syntastic_aggregate_errors = 0
syntastic: 273300.369049: getcwd() = /Users/r631269/Documents/repos/stack-formation/src/condensers/helpers
syntastic: 273300.369360: CacheErrors: Invoking checker: python/flake8
syntastic: 273300.369993: SyntasticMake: called with options: {'errorformat': '%E%f:%l: could not compile,%-Z%p^,%A%f:%l:%c: %t%n %m,%A%f:%l: %t%n %m,%-G%.%#', 'makeprg': 'flake8
tasks.py', 'env': {'TERM': 'dumb'}}
syntastic: 273300.631388: checker output: ['Traceback (most recent call last):', '  File "/usr/local/bin/flake8", line 11, in <module>', '    sys.exit(main())', '  File "/usr/loca
l/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main', '    app.run(argv)', '  File "/usr/local/lib/python2.7/site-packages/flake8/main/application.py", line 396, i
n run', '    self._run(argv)', '  File "/usr/local/lib/python2.7/site-packages/flake8/main/application.py", line 383, in _run', '    self.initialize(argv)', '  File "/usr/local/li
b/python2.7/site-packages/flake8/main/application.py", line 365, in initialize', '    self.find_plugins()', '  File "/usr/local/lib/python2.7/site-packages/flake8/main/application
.py", line 177, in find_plugins', '    self.prelim_opts.isolated,', '  File "/usr/local/lib/python2.7/site-packages/flake8/options/config.py", line 328, in get_local_plugins', '
  config = config_finder.local_configs()', '  File "/usr/local/lib/python2.7/site-packages/flake8/options/config.py", line 126, in local_configs', '    config, found_files = self.
_read_config(self.local_config_files())', '  File "/usr/local/lib/python2.7/site-packages/flake8/options/config.py", line 69, in _read_config', '    found_files.extend(config.read
(filename))', '  File "/usr/local/lib/python2.7/site-packages/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py", line 704, in read', '    with open(filename, encodi
ng=encoding) as fp:', 'LookupError: unknown encoding: ', '']
syntastic: 273300.633431: raw loclist: []
syntastic: 273300.633808: getLocList: checker python/flake8 returned 1
syntastic: 273300.634019: python/flake8 raw: []
syntastic: 273300.634296: quiet_messages filter: {}
syntastic: 273300.634624: aggregated: {'_sorted': 0, '_name': '', '_owner': 70, '_columns': 1, '_rawLoclist': []}
```

SyntasticInfo
```Syntastic version: 3.6.0
Info for filetype: python
Global mode: active
Filetype python is active
The current file will be checked automatically
Available checkers: flake8 pep8 pyflakes pylint python
Currently enabled checker: flake8

**Comment by lcd047** [comment]
> `'  File "/usr/local/lib/python2.7/site-packages/configparser-3.5.0-py2.7.egg/backports/configparser/__init__.py", line 704, in read', '    with open(filename, encoding=encoding) as fp:', 'LookupError: unknown encoding: ', '']`

This is a problem between your Vim, your Python, and `flake8`.  Fix it, and syntastic will start working.  See also #902 for a similar problem.

**Comment by r631269** [comment]
for anyone else who finds this issue, it was fixed by adding `export LC_CTYPE=en_US.UTF-8` to by ~/.bashrc
