### ISSUE TITLE
syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)

### ISSUE THREAD

**Issue by Raoul555** [vim-syntastic/syntastic#2128]
Having this error in vim:
`syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)`

Didn't find solution in other ticket related.

Details:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"sib.py" 26L, 1178C
syntastic: error: checker output:
This option u'required-attributes' will be removed in Pylint 2.0This option u'ignore-iface-meth
ods' will be removed in Pylint 2.0pylint 1.6.5,
astroid 1.4.9
Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118]
syntastic: error: checker python/pylint: can't parse version string (abnormal termination?)
syntastic: 28.960523: g:syntastic_version = '3.8.0-2 (Vim 800, Linux, GUI)'
syntastic: 28.960699: &shell = '/bin/bash', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &sh
ellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &sh
ellxescape = ''
syntastic: 28.961280: UpdateErrors: python
syntastic: 28.961564: CacheErrors: python
syntastic: 28.962192: g:syntastic_aggregate_errors = 0
syntastic: 28.962376: getcwd() = '/home/bree'
syntastic: 28.972093: system: command run in 0.009025s
syntastic: 28.972523: CacheErrors: Invoking checker: python/python
syntastic: 28.973282: SyntasticMake: called with options: {'errorformat': '%E%f:%l:%c: %m', 'ma
keprg': 'python /srv/tools/share/dotfiles/vim/bundle/syntastic/syntax_checkers/python/compile.p
y sib.py', 'env': {'TERM': 'dumb'}, 'returns': [0]}
syntastic: 29.005239: system: command run in 0.031536s
syntastic: 29.005729: getLocList: checker python/python returned 0
syntastic: 29.006005: getLocList: checker python/python run in 0.033338s
```

What's wrong?

Thanks

**Comment by lcd047** [comment]
Please see #1950.  If that doesn't point you to a solution please run `pylint --version` in a terminal and post the output.

**Comment by Raoul555** [comment]
I tried to redirect it to dev/null. Now, no error on vim startup, but synsatix check is not working.

`$ pylint --version
This option u'required-attributes' will be removed in Pylint 2.0This option u'ignore-iface-methods' will be removed in Pylint 2.0pylint 1.6.5, 
astroid 1.4.9
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]`

**Comment by lcd047** [comment]
> I tried to redirect it to dev/null.

Then please consider reading again the post I mentioned.

**Comment by neverho0d** [comment]
The file I was working on was named "stat.py" and the name was the source of the issue:
```
$ pylint --version
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/home/snipesoft/.pyenv/versions/3.8.0/lib/python3.8/site.py", line 580, in <module>
    main()
  File "/home/snipesoft/.pyenv/versions/3.8.0/lib/python3.8/site.py", line 563, in main
    known_paths = venv(known_paths)
  File "/home/snipesoft/.pyenv/versions/3.8.0/lib/python3.8/site.py", line 468, in venv
    candidate_confs = [
  File "/home/snipesoft/.pyenv/versions/3.8.0/lib/python3.8/site.py", line 473, in <listcomp>
    if os.path.isfile(conffile)
  File "/home/snipesoft/.pyenv/versions/3.8.0/lib/python3.8/genericpath.py", line 33, in isfile
    return stat.S_ISREG(st.st_mode)
AttributeError: module 'stat' has no attribute 'S_ISREG'
```

The issue was gone after renaming the file to another name.
